name: Sonatype SCA Scanning for FDC3

on:
  workflow_dispatch:
  pull_request_target:
  push:

env:
  SonatypeUrl: "https://finos.sonatype.app/platform/"
  SonatypeAppId: "fdc3"
  ExcludeDirectory: ""

jobs:
  scan-java:
    name: Build and Scan with Sonatype
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install --omit=dev
      
      - run: npm install --omit=dev
        working-directory: toolbox/fdc3-workbench

      - run: npm install --omit=dev
        working-directory: website

      # - run: npm i --package-lock-only
          
      - name: Sonatype Lifecycle SCA Scan
        if: always()
        # if: github.repository_owner == 'finos'
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          stage: "build"
          scan-targets: .
          # scan-targets: "package-lock.json website/package-lock.json toolbox/fdc3-workbench/package-lock.json"
          module-exclude: ${{ env.ExcludeDirectory }}
          sarif-file: sonatype-results.sarif
          upload-sarif-file: true
          
      - name: Save Sonatype SBOM
        if: steps.evaluate.outputs.scan-id && always() 
        uses: sonatype/actions/fetch-sbom@v1
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          scan-id: ${{ steps.evaluate.outputs.scan-id }}
          sbom-standard: spdx
          sbom-version: 2.3
          artifact-name: ${{ env.SonatypeAppId }}-sonatype-bom
          
